version: '3.8'

services:
  frontend:
    container_name: clonet-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: clonet-frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - clonet-network

  backend:
    container_name: clonet-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: clonet-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - ./data/parquet:/app/data/parquet
      - ./data/delta:/app/data/delta
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=clonet_db
      - PORT=5000
      - SPARK_SERVICE_URL=http://spark-service:8000
    deploy:
      resources:
        limits:
          memory: 2G
    depends_on:
      mysql:
        condition: service_healthy
      spark-service:
        condition: service_healthy
    networks:
      - clonet-network

  spark-service:
    container_name: clonet-spark-service
    build:
      context: ./spark-service
      dockerfile: Dockerfile
    image: clonet-spark-service:latest
    ports:
      - "8000:8000"  # Flask API
      - "4040:4040"  # Spark UI
    volumes:
      - ./data/parquet:/data/parquet
      - ./data/delta:/data/delta
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=clonet_db
    deploy:
      resources:
        limits:
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - clonet-network

  mysql:
    container_name: clonet-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: clonet_db
      MYSQL_USER: clonet_user
      MYSQL_PASSWORD: clonet_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - clonet-network

  sqlserver:
    container_name: clonet-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Password123!", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - clonet-network

networks:
  clonet-network:
    driver: bridge

volumes:
  frontend_node_modules:
  backend_node_modules:
  mysql_data:
  sqlserver_data: