openapi: 3.0.0
info:
  title: Clonet API
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
paths:
  /connections:
    get:
      summary: Get all connections
      responses:
        '200':
          description: List of connections
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Connection'
    post:
      summary: Add a new connection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Connection'
      responses:
        '201':
          description: Connection created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Connection'
  /connections/{id}:
    get:
      summary: Get a connection by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Connection details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Connection'
    put:
      summary: Update a connection
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Connection'
      responses:
        '200':
          description: Connection updated
    delete:
      summary: Delete a connection
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Connection deleted
components:
  schemas:
    Connection:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        host:
          type: string
        port:
          type: string
        user:
          type: string
        password:
          type: string
        db_name:
          type: string
        type:
          type: string
